[tool.poetry]
name = "aoc"
version = "0.1.0"
description = "Advent of Code 2022"
authors = ["Pedro Lopez Mareque <pedro.lopez@clarity.ai>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
expects = "^0.9.0"
pytest-xdist = "^3.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
